/**
 * This file generated by https://github.com/rmlzy/form-builder
 */
import React from "react";
import { Button, Row, Divider, Breadcrumb, Steps, Form, Input, Rate, Radio, Table } from "antd";

class AwesomeForm extends React.Component {
  render() {
    return (
      <Form layout="vertical">
        <Breadcrumb separator="/">
          <Breadcrumb.Item>首页</Breadcrumb.Item>
          <Breadcrumb.Item>模块A</Breadcrumb.Item>
          <Breadcrumb.Item>页面B</Breadcrumb.Item>
        </Breadcrumb>
        <Button htmlType="button" size="middle" type="primary">
          按钮
        </Button>
        <Divider dashed={false} type="horizontal"></Divider>

        <Form.Item label="输入框">
          <Input type="text" />
        </Form.Item>

        <p>这是一个段落</p>

        <Form.Item label="单选框">
          <Radio.Group name="field">
            <Radio value="field1">选项1</Radio>,<Radio value="field2">选项2</Radio>,<Radio value="field3">选项3</Radio>
          </Radio.Group>
        </Form.Item>

        <Row gutter={gutter}>{children}</Row>

        <Steps current={0} direction="horizontal" labelPlacement="horizontal">
          <Steps.Step title="第一步" subTitle="副标题" />
          <Steps.Step title="第二步" subTitle="副标题" />
          <Steps.Step title="第三步" subTitle="副标题" />
        </Steps>

        <Form.Item label="文本域">
          <Input.TextArea rows={4} />
        </Form.Item>

        <Form.Item label="评分">
          <Rate allowClear={true} allowHalf={false} count={5} />
        </Form.Item>

        <Table
          size="middle"
          dataSource={[
            { index: 0, name: "Mock Data 0", age: "Mock Data 0", address: "Mock Data 0" },
            { index: 1, name: "Mock Data 1", age: "Mock Data 1", address: "Mock Data 1" },
            { index: 2, name: "Mock Data 2", age: "Mock Data 2", address: "Mock Data 2" },
            { index: 3, name: "Mock Data 3", age: "Mock Data 3", address: "Mock Data 3" },
            { index: 4, name: "Mock Data 4", age: "Mock Data 4", address: "Mock Data 4" },
            { index: 5, name: "Mock Data 5", age: "Mock Data 5", address: "Mock Data 5" },
            { index: 6, name: "Mock Data 6", age: "Mock Data 6", address: "Mock Data 6" },
            { index: 7, name: "Mock Data 7", age: "Mock Data 7", address: "Mock Data 7" },
            { index: 8, name: "Mock Data 8", age: "Mock Data 8", address: "Mock Data 8" },
            { index: 9, name: "Mock Data 9", age: "Mock Data 9", address: "Mock Data 9" },
          ]}
          columns={[
            { title: "姓名", dataIndex: "name", key: "name" },
            { title: "年龄", dataIndex: "age", key: "age" },
            { title: "住址", dataIndex: "address", key: "address" },
          ]}
          pagination={true}
        />
      </Form>
    );
  }
}

export default AwesomeForm;
